# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
xcversion(version: "~> 12.0")
sync_code_signing(type: "development")
sync_code_signing(type: "enterprise")
cocoapods()

platform :ios do
  desc "dev for inHouse"
  lane :dev do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: "enterprise", export_options: {
      provisioningProfiles: {
        "com.enterprise.kanhan.test.green" => "match InHouse com.enterprise.kanhan.test.green"
      }
    })
    # upload_to_testflight
  end
  desc "uat for inHouse"
  lane :uat do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: "enterprise", export_options: {
      provisioningProfiles: {
        "com.enterprise.kanhan.test.green" => "match InHouse com.enterprise.kanhan.test.green"
      }
    })
    # upload_to_testflight
  end
  desc "prod for inHouse"
  lane :prod do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: "enterprise", export_options: {
      provisioningProfiles: {
        "com.enterprise.kanhan.test.green" => "match InHouse com.enterprise.kanhan.test.green"
      }
    })
    # upload_to_testflight
  end
end
